version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dinor-dashboard
    container_name: dinor-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dinor-network
    depends_on:
      - db
      - redis
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: dinor-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dinor_dashboard
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: dinor
    volumes:
      - dinor-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dinor-network

  redis:
    image: redis:7-alpine
    container_name: dinor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dinor-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dinor-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: dinor
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - dinor-network
    depends_on:
      - db

networks:
  dinor-network:
    driver: bridge

volumes:
  dinor-db-data:
    driver: local 